"use client";

import { useState } from "react";
import { useForm, Controller } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { useRouter } from "next/navigation";
import { toast } from "sonner";
import { useCategories } from "@/lib/api/equipmentService";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import { Loader2, Sparkles, AlertTriangle, AlertCircle, CheckCircle, Info, Zap } from "lucide-react";
import ImageUpload from "./ImageUpload";
import { EquipmentStatus } from "@/types";
import { useGenerateDescription, useAnalyzeListing, ListingAnalysisResponse } from "@/lib/api/aiService";

const currentYear = new Date().getFullYear();

// ---- Zod Form Schema ----

const equipmentFormSchema = z.object({
  name: z.string().min(1, "Equipment name is required").max(150),
  brand: z.string().min(1, "Brand is required"),
  model: z.string().min(1, "Model is required"),
  manufactureYear: z
    .number({ message: "Manufacture year is required" })
    .min(1900, "Manufacture year must be at least 1900")
    .max(currentYear, `Manufacture year cannot exceed ${currentYear}`),
  categoryId: z.number({ message: "Category is required" }).positive("Select a category"),
  description: z.string().min(1, "Description is required").max(2000),
  dailyRentalPrice: z
    .number({ message: "Daily rental price is required" })
    .positive("Rental price must be positive"),
  location: z.string().min(1, "Location address is required"),
  availabilityStatus: z.enum(["AVAILABLE", "BOOKED", "MAINTENANCE", "UNAVAILABLE"] as const),
  imageUrls: z.array(z.string()).min(1, "At least one equipment image is required"),
});

export type EquipmentFormValues = z.infer<typeof equipmentFormSchema>;

interface EquipmentFormProps {
  initialValues?: Partial<EquipmentFormValues>;
  onSubmit: (values: EquipmentFormValues) => Promise<void>;
  isSubmitting: boolean;
  submitButtonText?: string;
}

export default function EquipmentForm({
  initialValues,
  onSubmit,
  isSubmitting,
  submitButtonText = "Save Listing",
}: EquipmentFormProps) {
  const router = useRouter();
  const { data: categories = [], isLoading: loadingCategories } = useCategories();

  const {
    register,
    handleSubmit,
    control,
    setValue,
    watch,
    formState: { errors },
  } = useForm<EquipmentFormValues>({
    resolver: zodResolver(equipmentFormSchema),
    defaultValues: {
      name: "",
      brand: "",
      model: "",
      manufactureYear: currentYear,
      description: "",
      dailyRentalPrice: 1000,
      location: "",
      availabilityStatus: "AVAILABLE",
      imageUrls: [],
      ...initialValues,
    },
  });

  const [isGenerating, setIsGenerating] = useState(false);
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [analysisResult, setAnalysisResult] = useState<ListingAnalysisResponse | null>(null);

  const generateDescriptionMutation = useGenerateDescription();
  const analyzeListingMutation = useAnalyzeListing();

  const watchedValues = watch();
  const selectedPowerType = watch("powerType") || "DIESEL";
  const isDiesel = selectedPowerType === "DIESEL";

  const handleGenerateDescription = async () => {
    if (!watchedValues.name || !watchedValues.brand || !watchedValues.model || !watchedValues.categoryId) {
      toast.error("Please fill Equipment Name, Brand, Model, and select a Category first.");
      return;
    }

    setIsGenerating(true);
    const categoryName = categories.find((c) => c.id === watchedValues.categoryId)?.name || "";

    try {
      const res = await generateDescriptionMutation.mutateAsync({
        name: watchedValues.name,
        brand: watchedValues.brand,
        model: watchedValues.model,
        category: categoryName,
        manufactureYear: Number(watchedValues.manufactureYear),
        dailyRentalPrice: Number(watchedValues.dailyRentalPrice),
        location: watchedValues.location || "Not specified",
      });

      const formatted = `### ${res.professionalTitle}

**Description:**
${res.professionalDescription}

**Key Features:**
${res.keyFeatures}

**Recommended Usage:**
${res.recommendedUsage}

**Safety Notes:**
${res.safetyNotes}`;

      setValue("description", formatted);
      toast.success("Description Generated by AI!");
    } catch (err: any) {
      const msg = err?.response?.data?.message || "Failed to generate description. Please try again.";
      toast.error(msg);
    } finally {
      setIsGenerating(false);
    }
  };

  const handleAnalyzeListing = async () => {
    setIsAnalyzing(true);
    const categoryName = categories.find((c) => c.id === watchedValues.categoryId)?.name || "";

    try {
      const res = await analyzeListingMutation.mutateAsync({
        name: watchedValues.name || "Unnamed machinery",
        description: watchedValues.description || "No description provided",
        imagesCount: watchedValues.imageUrls?.length || 0,
        price: Number(watchedValues.dailyRentalPrice) || 0,
        location: watchedValues.location || "Not specified",
        category: categoryName || "Not specified",
      });

      setAnalysisResult(res);
      toast.success("Analysis Complete!");
    } catch (err: any) {
      const msg = err?.response?.data?.message || "Failed to analyze listing. Please try again.";
      toast.error(msg);
    } finally {
      setIsAnalyzing(false);
    }
  };

  const onFormSubmit = async (data: EquipmentFormValues) => {
    try {
      await onSubmit(data);
    } catch (err: any) {
      const message = err?.response?.data?.message || "Operation failed. Please try again.";
      toast.error(message);
    }
  };

  return (
    <form onSubmit={handleSubmit(onFormSubmit)} className="space-y-6" noValidate>
      {/* Name, Brand, Model */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div className="space-y-1.5">
          <Label htmlFor="name">Equipment Name</Label>
          <Input
            id="name"
            placeholder="e.g. Caterpillar 320D"
            aria-invalid={!!errors.name}
            {...register("name")}
          />
          {errors.name && <p className="text-xs text-destructive">{errors.name.message}</p>}
        </div>

        <div className="space-y-1.5">
          <Label htmlFor="brand">Brand</Label>
          <Input
            id="brand"
            placeholder="e.g. CAT"
            aria-invalid={!!errors.brand}
            {...register("brand")}
          />
          {errors.brand && <p className="text-xs text-destructive">{errors.brand.message}</p>}
        </div>

        <div className="space-y-1.5">
          <Label htmlFor="model">Model</Label>
          <Input
            id="model"
            placeholder="e.g. 320D"
            aria-invalid={!!errors.model}
            {...register("model")}
          />
          {errors.model && <p className="text-xs text-destructive">{errors.model.message}</p>}
        </div>
      </div>

      {/* Year, Category, Price */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div className="space-y-1.5">
          <Label htmlFor="manufactureYear">Manufacture Year</Label>
          <Input
            id="manufactureYear"
            type="number"
            placeholder="e.g. 2021"
            aria-invalid={!!errors.manufactureYear}
            {...register("manufactureYear", { valueAsNumber: true })}
          />
          {errors.manufactureYear && (
            <p className="text-xs text-destructive">{errors.manufactureYear.message}</p>
          )}
        </div>

        <div className="space-y-1.5">
          <Label htmlFor="categoryId">Category</Label>
          {loadingCategories ? (
            <div className="h-10 border rounded bg-muted animate-pulse flex items-center px-3 text-xs text-muted-foreground">
              Loading categories…
            </div>
          ) : (
            <select
              id="categoryId"
              className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
              aria-invalid={!!errors.categoryId}
              {...register("categoryId", { valueAsNumber: true })}
            >
              <option value="">Select Category</option>
              {categories.map((cat) => (
                <option key={cat.id} value={cat.id}>
                  {cat.name}
                </option>
              ))}
            </select>
          )}
          {errors.categoryId && <p className="text-xs text-destructive">{errors.categoryId.message}</p>}
        </div>

        <div className="space-y-1.5">
          <Label htmlFor="dailyRentalPrice">Daily Rental Price (₹)</Label>
          <Input
            id="dailyRentalPrice"
            type="number"
            placeholder="e.g. 5000"
            aria-invalid={!!errors.dailyRentalPrice}
            {...register("dailyRentalPrice", { valueAsNumber: true })}
          />
          {errors.dailyRentalPrice && (
            <p className="text-xs text-destructive">{errors.dailyRentalPrice.message}</p>
          )}
        </div>
      </div>

      {/* Location & Status */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <div className="space-y-1.5">
          <Label htmlFor="location">Location</Label>
          <Input
            id="location"
            placeholder="e.g. Bangalore, Karnataka"
            aria-invalid={!!errors.location}
            {...register("location")}
          />
          {errors.location && <p className="text-xs text-destructive">{errors.location.message}</p>}
        </div>

        <div className="space-y-1.5">
          <Label htmlFor="availabilityStatus">Availability Status</Label>
          <select
            id="availabilityStatus"
            suppressHydrationWarning
            className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
            {...register("availabilityStatus")}
          >
            <option value="AVAILABLE">Available</option>
            <option value="BOOKED">Booked</option>
            <option value="MAINTENANCE">Maintenance</option>
            <option value="UNAVAILABLE">Unavailable</option>
          </select>
        </div>
      </div>

      {/* Power Drive System & EV Specs */}
      <div className="p-4 rounded-xl border border-amber-500/20 bg-amber-500/5 space-y-4 font-sans">
        <div className="flex items-center justify-between">
          <h4 className="text-sm font-bold text-foreground flex items-center">
            <Zap className="w-4 h-4 text-amber-500 mr-2" /> Power Drive System & EV Charging Specs
          </h4>
          <Badge variant="outline" className="text-[10px] font-extrabold border-amber-500/30 text-amber-600 bg-amber-500/10 uppercase tracking-wider">
            {isDiesel ? "Standard Diesel Specs" : "Electric EV Specs Active"}
          </Badge>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <div className="space-y-1.5">
            <Label htmlFor="powerType" className="text-xs font-semibold text-foreground">Fuel / Drive System</Label>
            <select
              id="powerType"
              suppressHydrationWarning
              className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring font-semibold"
              {...register("powerType")}
            >
              <option value="DIESEL">⛽ Diesel Engine</option>
              <option value="ELECTRIC">⚡ 100% Zero-Emission Electric (EV)</option>
              <option value="HYBRID">🔋 Hybrid Diesel-Electric</option>
            </select>
          </div>

          <div className="space-y-1.5">
            <Label
              htmlFor="batteryCapacityKwh"
              className={`text-xs font-semibold ${isDiesel ? "text-muted-foreground" : "text-foreground"}`}
            >
              Battery Pack (kWh) {isDiesel && <span className="text-[10px] text-amber-600 font-bold">(EV Only)</span>}
            </Label>
            <Input
              id="batteryCapacityKwh"
              type="number"
              disabled={isDiesel}
              placeholder={isDiesel ? "N/A (Diesel Machinery)" : "e.g. 200"}
              className="bg-background border-input text-foreground text-sm disabled:opacity-50 disabled:bg-muted disabled:cursor-not-allowed"
              {...register("batteryCapacityKwh", { valueAsNumber: true })}
            />
          </div>

          <div className="space-y-1.5">
            <Label
              htmlFor="chargingType"
              className={`text-xs font-semibold ${isDiesel ? "text-muted-foreground" : "text-foreground"}`}
            >
              Charging Interface {isDiesel && <span className="text-[10px] text-amber-600 font-bold">(EV Only)</span>}
            </Label>
            <Input
              id="chargingType"
              type="text"
              disabled={isDiesel}
              placeholder={isDiesel ? "N/A (Diesel Machinery)" : "e.g. CCS2 DC Fast / 415V AC"}
              className="bg-background border-input text-foreground text-sm disabled:opacity-50 disabled:bg-muted disabled:cursor-not-allowed"
              {...register("chargingType")}
            />
          </div>
        </div>

        <div className={`flex items-center space-x-2 pt-2 border-t border-amber-500/20 ${isDiesel ? "opacity-50" : ""}`}>
          <input
            type="checkbox"
            id="evTermsAccepted"
            disabled={isDiesel}
            className="rounded border-input text-amber-500 focus:ring-amber-500 w-4 h-4 cursor-pointer disabled:cursor-not-allowed"
            {...register("evTermsAccepted")}
          />
          <Label
            htmlFor="evTermsAccepted"
            className={`text-xs text-muted-foreground ${isDiesel ? "cursor-not-allowed" : "cursor-pointer"}`}
          >
            I confirm compliance with <strong className="text-foreground">EquipLink EV Battery Health & State-of-Charge (80% SOC) Return SLA</strong> terms.
          </Label>
        </div>
      </div>

      {/* Description */}
      <div className="space-y-1.5">
        <div className="flex items-center justify-between">
          <Label htmlFor="description">Description</Label>
          <Button
            type="button"
            variant="ghost"
            size="xs"
            onClick={handleGenerateDescription}
            disabled={isGenerating}
            className="text-primary hover:text-primary/80 flex items-center space-x-1 font-bold text-xs"
          >
            {isGenerating ? (
              <>
                <Loader2 className="h-3 w-3 animate-spin mr-1" />
                Generating...
              </>
            ) : (
              <>
                <Sparkles className="h-3 w-3 mr-1 text-primary animate-pulse" />
                Generate with AI
              </>
            )}
          </Button>
        </div>
        <textarea
          id="description"
          placeholder="Describe your equipment specs, attachment support, and rental terms..."
          className="flex min-h-[100px] w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
          aria-invalid={!!errors.description}
          {...register("description")}
        />
        {errors.description && <p className="text-xs text-destructive">{errors.description.message}</p>}
      </div>

      {/* Image Upload Component */}
      <div className="space-y-1.5">
        <Label>Equipment Images (At least 1 required)</Label>
        <Controller
          name="imageUrls"
          control={control}
          render={({ field }) => (
            <ImageUpload
              value={field.value}
              onChange={field.onChange}
              maxFiles={5}
            />
          )}
        />
        {errors.imageUrls && <p className="text-xs text-destructive">{errors.imageUrls.message}</p>}
      </div>

      {/* AI Listing Analyzer Section */}
      <div className="border-t pt-6 space-y-4">
        <div className="flex items-center justify-between">
          <div>
            <h4 className="text-sm font-bold text-foreground">AI Listing Completeness Audit</h4>
            <p className="text-xs text-muted-foreground">Verify spelling, pricing realism, image assets counts, and get copy improvement proposals.</p>
          </div>
          <Button
            type="button"
            variant="outline"
            size="sm"
            onClick={handleAnalyzeListing}
            disabled={isAnalyzing}
            className="text-xs font-semibold"
          >
            {isAnalyzing ? (
              <>
                <Loader2 className="mr-1.5 h-3.5 w-3.5 animate-spin" />
                Analyzing...
              </>
            ) : (
              <>
                <Sparkles className="mr-1.5 h-3.5 w-3.5 text-primary" />
                Analyze Listing
              </>
            )}
          </Button>
        </div>

        {analysisResult && (
          <div className="bg-card border rounded-xl p-5 space-y-6 shadow-sm">
            {/* Score progress card */}
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-4 border-b">
              <div className="flex items-center space-x-4">
                <div className={`h-16 w-16 rounded-full flex items-center justify-center border-4 text-xl font-extrabold shrink-0 ${
                  analysisResult.overallScore >= 75
                    ? "border-emerald-500 text-emerald-600 dark:text-emerald-400 bg-emerald-50/10"
                    : analysisResult.overallScore >= 50
                    ? "border-amber-500 text-amber-600 dark:text-amber-400 bg-amber-50/10"
                    : "border-rose-500 text-rose-600 dark:text-rose-400 bg-rose-50/10"
                }`}>
                  {analysisResult.overallScore}%
                </div>
                <div>
                  <h5 className="font-bold text-sm">Listing Score</h5>
                  <p className="text-xs text-muted-foreground">Based on descriptions completeness, pricing realism, and image count.</p>
                </div>
              </div>
            </div>

            {/* Strengths & Weaknesses */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6 text-xs">
              <div className="space-y-2">
                <h6 className="font-bold text-emerald-600 dark:text-emerald-400 flex items-center">
                  <CheckCircle className="h-4 w-4 mr-1.5 shrink-0" /> Listing Strengths
                </h6>
                {analysisResult.strengths.length === 0 ? (
                  <p className="text-muted-foreground italic">None identified.</p>
                ) : (
                  <ul className="space-y-1 list-disc pl-4 text-muted-foreground">
                    {analysisResult.strengths.map((str, idx) => (
                      <li key={idx}>{str}</li>
                    ))}
                  </ul>
                )}
              </div>

              <div className="space-y-2">
                <h6 className="font-bold text-rose-600 dark:text-rose-400 flex items-center">
                  <AlertCircle className="h-4 w-4 mr-1.5 shrink-0" /> Areas for Improvement
                </h6>
                {analysisResult.weaknesses.length === 0 ? (
                  <p className="text-muted-foreground italic">None identified.</p>
                ) : (
                  <ul className="space-y-1 list-disc pl-4 text-muted-foreground">
                    {analysisResult.weaknesses.map((weak, idx) => (
                      <li key={idx}>{weak}</li>
                    ))}
                  </ul>
                )}
              </div>
            </div>

            {/* Suggestions & Missing Info */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6 text-xs border-t pt-4">
              <div className="space-y-2">
                <h6 className="font-bold text-foreground flex items-center">
                  <Info className="h-4 w-4 mr-1.5 shrink-0 text-primary" /> Suggestions
                </h6>
                {analysisResult.suggestions.length === 0 ? (
                  <p className="text-muted-foreground italic">None.</p>
                ) : (
                  <ul className="space-y-1 list-disc pl-4 text-muted-foreground">
                    {analysisResult.suggestions.map((sug, idx) => (
                      <li key={idx}>{sug}</li>
                    ))}
                  </ul>
                )}
              </div>

              <div className="space-y-2">
                <h6 className="font-bold text-amber-600 dark:text-amber-400 flex items-center">
                  <AlertTriangle className="h-4 w-4 mr-1.5 shrink-0" /> Missing Information
                </h6>
                {analysisResult.missingInformation.length === 0 ? (
                  <p className="text-muted-foreground italic">None.</p>
                ) : (
                  <ul className="space-y-1 list-disc pl-4 text-muted-foreground">
                    {analysisResult.missingInformation.map((miss, idx) => (
                      <li key={idx}>{miss}</li>
                    ))}
                  </ul>
                )}
              </div>
            </div>

            {/* Rewritten description suggestion */}
            {analysisResult.improvedDescriptionSuggestion && (
              <div className="border-t pt-4 space-y-3">
                <div className="flex items-center justify-between">
                  <h6 className="font-bold text-xs text-foreground">AI Improved Description Suggestion</h6>
                  <Button
                    type="button"
                    variant="outline"
                    size="xs"
                    onClick={() => {
                      setValue("description", analysisResult.improvedDescriptionSuggestion);
                      toast.success("Applied AI suggested description");
                    }}
                    className="text-[10px] h-7 px-2 font-bold"
                  >
                    Apply Suggestion
                  </Button>
                </div>
                <div className="p-3 bg-muted/30 border rounded-lg text-xs text-muted-foreground max-h-36 overflow-y-auto whitespace-pre-wrap leading-relaxed">
                  {analysisResult.improvedDescriptionSuggestion}
                </div>
              </div>
            )}
          </div>
        )}
      </div>

      {/* Buttons */}
      <div className="flex justify-end space-x-4 pt-4 border-t">
        <Button
          type="button"
          variant="outline"
          onClick={() => router.back()}
          disabled={isSubmitting}
        >
          Cancel
        </Button>
        <Button type="submit" disabled={isSubmitting}>
          {isSubmitting ? (
            <>
              <Loader2 className="mr-2 h-4 w-4 animate-spin" />
              Saving Listing…
            </>
          ) : (
            submitButtonText
          )}
        </Button>
      </div>
    </form>
  );
}
